name: create tag and relese

on:
  pull_request:
    types: [closed]
jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'PR') && startsWith(github.base_ref, 'master')
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_and_prepare_release
        uses: moble/github-tag-action@main
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: "v7.7.0"
      - name: Display
        run: echo ${{ steps.tag_and_prepare_release.outputs.new_tag }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag:  ${{ steps.tag_and_prepare_release.outputs.new_tag }}
          title: ${{ steps.tag_and_prepare_release.outputs.new_tag }}
          prerelease: false
          
